---
- hosts: localhost
  become: true
  gather_facts: false

  pre_tasks:
    - name: install roles
      local_action: command /home/ubuntu/.local/bin/ansible-galaxy --help #install -r /home/ubuntu/environment/end/roles/requirements.yml
      register: out
      
    - debug: var=out

  tasks:
    - include_role:
        name: nginxinc.nginx

  post_tasks:
    - name: Upload website files
      copy: src=../files/website/ dest=/usr/share/nginx/html/ mode=0644

    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: 80
        proto: tcp
